import {
  Business,
  User,
  Category,
  Supplier,
  Product,
  StockEntry,
  Sale,
  SaleItem,
} from "@/types";

export const dummyBusinesses: Business[] = [
  {
    id: 1,
    name: "TechStore Inc.",
    address: "123 Tech St, Silicon Valley",
    created_at: "2023-01-15T08:30:00Z",
    users_count: 4,
  },
  {
    id: 2,
    name: "Fashion Outlet",
    address: "456 Fashion Ave, New York",
    created_at: "2023-02-20T10:15:00Z",
    users_count: 3,
  },
  {
    id: 3,
    name: "Grocery World",
    address: "789 Food Blvd, Chicago",
    created_at: "2023-03-10T09:45:00Z",
    users_count: 5,
  },
];

export const dummyUsers: User[] = [
  {
    id: 1,
    email: "admin@techstore.com",
    full_name: "John Admin",
    phone: "+1234567890",
    business: 1,
    business_details: dummyBusinesses[0],
    role: "admin",
    role_display: "Administrator",
    is_active: true,
    date_joined: "2023-01-16T09:00:00Z",
    last_login: "2023-04-18T14:30:00Z",
  },
  {
    id: 2,
    email: "manager@techstore.com",
    full_name: "Sarah Manager",
    phone: "+1987654321",
    business: 1,
    business_details: dummyBusinesses[0],
    role: "manager",
    role_display: "Manager",
    is_active: true,
    date_joined: "2023-01-20T10:00:00Z",
    last_login: "2023-04-17T16:45:00Z",
  },
  {
    id: 3,
    email: "staff@techstore.com",
    full_name: "Mike Staff",
    phone: "+1122334455",
    business: 1,
    business_details: dummyBusinesses[0],
    role: "staff",
    role_display: "Staff",
    is_active: true,
    date_joined: "2023-02-05T11:30:00Z",
    last_login: "2023-04-18T09:15:00Z",
  },
];

export const dummyCategories: Category[] = [
  { id: 1, name: "Electronics", description: "Electronic devices and gadgets" },
  {
    id: 2,
    name: "Computers",
    description: "Laptops, desktops and accessories",
  },
  { id: 3, name: "Mobile Phones", description: "Smartphones and accessories" },
  {
    id: 4,
    name: "Home Appliances",
    description: "Kitchen and home electronics",
  },
];

export const dummySuppliers: Supplier[] = [
  {
    id: 1,
    name: "TechSupply Corp",
    contact_person: "Robert Smith",
    email: "robert@techsupply.com",
    phone: "+1212333444",
    address: "100 Supply St, San Francisco, CA",
  },
  {
    id: 2,
    name: "Global Electronics",
    contact_person: "Jessica Brown",
    email: "jessica@globalelec.com",
    phone: "+1415666777",
    address: "200 Global Ave, Seattle, WA",
  },
  {
    id: 3,
    name: "Digital World",
    contact_person: "Alex Johnson",
    email: "alex@digitalworld.com",
    phone: "+1628999000",
    address: "300 Digital Blvd, Austin, TX",
  },
];

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: "Laptop Pro X",
    sku: "LPX-001",
    image: "/assets/laptop.jpg",
    description: "High-performance laptop with 16GB RAM and 512GB SSD",
    category: 2,
    category_name: "Computers",
    supplier: 1,
    supplier_name: "TechSupply Corp",
    stock: 25,
    reorder_level: 5,
    cost_price: 800,
    selling_price: 1200,
    profit_margin: 50,
    stock_value: 20000,
    needs_reorder: false,
    is_active: true,
  },
  {
    id: 2,
    name: "Smartphone Ultra",
    sku: "SPU-002",
    image: "/assets/smartphone.jpg",
    description: "6.7-inch display, 128GB storage, 12MP camera",
    category: 3,
    category_name: "Mobile Phones",
    supplier: 2,
    supplier_name: "Global Electronics",
    stock: 3,
    reorder_level: 5,
    cost_price: 500,
    selling_price: 899,
    profit_margin: 79.8,
    stock_value: 1500,
    needs_reorder: true,
    is_active: true,
  },
  {
    id: 3,
    name: 'Smart TV 55"',
    sku: "STV-003",
    image: "/assets/tv.jpg",
    description: "55-inch 4K Smart TV with HDR",
    category: 1,
    category_name: "Electronics",
    supplier: 3,
    supplier_name: "Digital World",
    stock: 12,
    reorder_level: 3,
    cost_price: 400,
    selling_price: 699,
    profit_margin: 74.75,
    stock_value: 4800,
    needs_reorder: false,
    is_active: true,
  },
  {
    id: 4,
    name: "Coffee Maker",
    sku: "CM-004",
    image: "/assets/coffeemaker.jpg",
    description: "Programmable coffee maker with thermal carafe",
    category: 4,
    category_name: "Home Appliances",
    supplier: 1,
    supplier_name: "TechSupply Corp",
    stock: 0,
    reorder_level: 5,
    cost_price: 60,
    selling_price: 99.99,
    profit_margin: 66.65,
    stock_value: 0,
    needs_reorder: true,
    is_active: true,
  },
];

export const dummyStockEntries: StockEntry[] = [
  {
    id: 1,
    product: 1,
    product_name: "Laptop Pro X",
    quantity: 10,
    unit_cost: 800,
    date_added: "2023-03-15T10:00:00Z",
    created_by: 1,
    notes: "Test",
  },
  {
    id: 2,
    product: 2,
    product_name: "Smartphone Ultra",
    quantity: 15,
    unit_cost: 500,
    date_added: "2023-03-20T11:30:00Z",
    created_by: 1,
  },
  {
    id: 3,
    product: 3,
    product_name: 'Smart TV 55"',
    quantity: 5,
    unit_cost: 400,
    date_added: "2023-04-01T09:15:00Z",
    created_by: 2,
  },
];

export const dummySaleItems: SaleItem[] = [
  {
    id: 1,
    product: 1,
    product_name: "Laptop Pro X",
    quantity: 1,
    unit_price: 1200,
    subtotal: 1200,
  },
  {
    id: 2,
    product: 2,
    product_name: "Smartphone Ultra",
    quantity: 2,
    unit_price: 899,
    subtotal: 1798,
  },
];

export const dummySales: Sale[] = [
  {
    id: 1,
    customer_name: "Jane Doe",
    customer_phone: "+1123456789",
    sale_date: "2023-04-10T14:30:00Z",
    total_amount: 1200,
    amount_paid: 1200,
    balance: 0,
    payment_method: "Credit Card",
    created_by: 2,
    items: [dummySaleItems[0]],
    invoice_number: "1122334455",
    payment_status: "paid",
  },
  {
    id: 2,
    customer_name: "Tom Smith",
    customer_phone: "+1987654321",
    sale_date: "2023-04-12T16:45:00Z",
    total_amount: 1798,
    amount_paid: 1500,
    balance: 298,
    payment_method: "Cash",
    created_by: 3,
    items: [dummySaleItems[1]],
    payment_status: "paid",

    invoice_number: "1122334456",
  },
  {
    id: 3,
    customer_name: "Alice Johnson",
    customer_phone: "+1456789012",
    sale_date: "2023-04-15T10:15:00Z",
    total_amount: 2998,
    amount_paid: 2998,
    balance: 0,
    payment_method: "Bank Transfer",
    created_by: 1,
    payment_status: "paid",
    items: [...dummySaleItems],

    invoice_number: "1122334457",
  },
];
